siteName: Miausairovi Cattery
siteDescription: >-
  GCCF Registered British Shorthair and Scottish Fold breeder based in
  Peterborough, UK. Ethical breeding practices, health-tested cats, and
  exceptional care for all our kittens.
contactEmail: info@miausairovi.com
contactPhone: ''
address: >-
  Peterborough, Cambridgeshire, UK
socialMedia:
  facebook: https://facebook.com/miausairovi
  instagram: https://instagram.com/miausairovi
  youtube: ''
