siteName: Miausairovi Cattery
siteDescription: >-
  GCCF Registered British Shorthair, British Longhair, Scottish Fold and Scottish Straight breeder based in
  Peterborough, UK. Ethical breeding practices, health-tested cats, and
  exceptional care for all our kittens.
contactEmail: info@miausairovi.com
contactPhone: ''
address: >-
  Peterborough, Cambridgeshire, UK
socialMedia:
  facebook: https://facebook.com/miausairovi
  instagram: https://instagram.com/miausairovi
  youtube: ''
